merge from ups (#1)
* Releasing 3.4.2

* Releasing 3.5.0-SNAPSHOT

* add serialVersionsUID

add serialVersionUID to nested class of KeyValue.

* Releasing 3.5.0.Beta1

* Releasing 3.5.0-SNAPSHOT

* Expose AsyncMap keys, values and entries

See https://github.com/eclipse/vert.x/issues/2020

* Removed traces

* Implement AsyncMapStream

* Autoclose AsyncMapStream when it ends or fails

* Remove AsyncMapStream, release resources with null data handler

* Removed key/value/entry streams, not well supported

* Update parent pom to 27

* Improve dependencies

* Releasing 3.5.0

* Releasing 3.5.1-SNAPSHOT

* ClusterWideMapTest renamed

Also, on this cluster manager, putWithTtlThenPut is not supported

* Added ZKClusteredSessionHandlerTest

* Don't fail too fast

* Releasing 3.5.1

* Releasing 3.6.0-SNAPSHOT

* Use plain adocs + simplify the build

* Use ContextInternal instead of ContextImpl

ContextImpl is no longer visible.

* Use parent pom version 34

* Improve configuration of surefire

* Update to use the correct executeBlockingInternal method

* Remove link to in-source docs

* Fix for LockTest.testAcquireDifferentLocksOnSameEventLoop

Follows-up on eclipse/vert.x#2482

* Upgrade stack to Guava 20.0 (see vert-x3/issues/#381)

* add unimplements method

Signed-off-by: stream <stream1984@gmail.com>

* restore node when reconnected

* refactor same code

* Moved classes to new clustering tests packages

* fix HA bug.

Signed-off-by: stream <stream1984@gmail.com>

* Releasing 3.6.0.CR1

* Releasing 3.6.0-SNAPSHOT

* Releasing 3.6.0.CR2

* Releasing 3.6.0-SNAPSHOT

* Releasing 3.6.0

* Releasing 4.0.0-SNAPSHOT

* fix issue #17

Signed-off-by: stream <stream1984@gmail.com>

* check conflict to avoid repeat clean node.

Signed-off-by: stream <stream1984@gmail.com>

* add CI travis

Signed-off-by: stream <stream1984@gmail.com>

* Updated Zookeeper version (#78)

* Use internal logging API

Signed-off-by: Thomas Segismont <tsegismo@redhat.com>

* Remove completer() usage

* Travis Maven cache

* Promise for Vert.x - see https://github.com/vert-x3/issues/issues/469

* EventBus request method for request-response pattern

* Travis SNAPSHOT deploy job should use OpenJDK8

* add zk sync action for SyncMap operation.

Signed-off-by: stream <stream1984@gmail.com>

* Releasing 4.0.0-milestone1

* Releasing 4.0.0-SNAPSHOT

* Releasing 4.0.0-milestone2

* Releasing 4.0.0-SNAPSHOT

* Releasing 4.0.0-milestone3

* Releasing 4.0.0-SNAPSHOT

* Update to latest vertx-core changes

* Update to latest cluster manager changes

* Use future in AsyncMap

* Releasing 4.0.0-milestone4

* Releasing 4.0.0-SNAPSHOT

* upgrade zk version to 3.5.x

Signed-off-by: XiaoXi.Liu <stream@boaRiver.local>

* fix TTL with zk 3.5.x

Signed-off-by: XiaoXi.Liu <stream@boaRiver.local>

* Added a dedicated executor to release locks (#91)

This avoids worker starvation when lock concurrency is greater than worker pool size.

See eclipse-vertx/vert.x#3126

* guava update see: https://github.com/vert-x3/issues/issues/516

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>

* Use Future#onComplete

* Use Future#onComplete

* Upgrade to curator 2.13.0 and only curator-test uses Guava

* Curator shades Guava so classes are shaded but the dependency still remains

* Missing guava lib caused NoClassDefFoundError in 3.9.0 - closes #95

* Remove setClustered(true) that was removed in vertx-core so it compiles again

* Use same version of zookeeper

* Update parent pom version

* Add automatic module name

Signed-off-by: afloarea <adrianfloarea07@yahoo.com>

* Port removeIfPresent fix from 3.9

See d87aec2

* Bump junit from 4.12 to 4.13.1

Bumps [junit](https://github.com/junit-team/junit4) from 4.12 to 4.13.1.
- [Release notes](https://github.com/junit-team/junit4/releases)
- [Changelog](https://github.com/junit-team/junit4/blob/main/doc/ReleaseNotes4.12.md)
- [Commits](https://github.com/junit-team/junit4/compare/r4.12...r4.13.1)

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: Stream <stream1984@me.com>
Co-authored-by: Julien Viet <julien@julienviet.com>
Co-authored-by: Thomas Segismont <tsegismo@redhat.com>
Co-authored-by: Thomas Segismont <tsegismont@gmail.com>
Co-authored-by: stream <stream1984@gmail.com>
Co-authored-by: lihui <lihui920913@qq.com>
Co-authored-by: Paolo Patierno <ppatierno@live.com>
Co-authored-by: XiaoXi.Liu <stream@boaRiver.local>
Co-authored-by: Paulo Lopes <pmlopes@gmail.com>
Co-authored-by: Paulo Lopes <pmlopes@users.noreply.github.com>
Co-authored-by: afloarea <adrianfloarea07@yahoo.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>